### ISSUE TITLE
Kódlefedettség tesztelés IncredibleK

### ISSUE THREAD

**Issue by IncredibleK** [BME-MIT-IET/Red-Frogs-iet-2019#10]
Tesztek kódlefedettségének mérése és ez alapján tesztkészlet bővítése

**Comment by IncredibleK** [comment]
Az elvégzett munka itt elérhető: [wiki](https://github.com/BME-MIT-IET/Red-Frogs-iet-2019/wiki/Tesztek-k%C3%B3dlefedetts%C3%A9g%C3%A9nek-m%C3%A9r%C3%A9se-%C3%A9s-ez-alapj%C3%A1n-tesztk%C3%A9szlet-b%C5%91v%C3%ADt%C3%A9se---IncredibleK)

**Comment by mabeto** [comment]
Az autómatizált tesztek megfelelően futottak

**Comment by TZsolt94** [comment]
A tesztek növelték a kódlefedettséget és sikeresen futottak.
