### ISSUE TITLE
Kódlefedettség tesztelés GalfiA

### ISSUE THREAD

**Issue by GalfiA** [BME-MIT-IET/Red-Frogs-iet-2019#11]
A kódlefedettség javítására készített tesztek a [wikin ](https://github.com/BME-MIT-IET/Red-Frogs-iet-2019/wiki/Tesztek-kódlefedettségének-mérése-és-ez-alapján-tesztkészlet-bővítése-GalfiA
)elérhetőek

**Comment by TZsolt94** [comment]
Jók a tesztek. (Esetleg amin lehetne javítani, hogy a ScheduledAction-ben a tesztek nevei utalhatnának jobban a tesztek közötti különbségekre)

**Comment by IncredibleK** [comment]
Nagyon jó lett, jó nyaralást!
