### ISSUE TITLE
Manuális tesztelés eredményei (mabeto)

### ISSUE THREAD

**Issue by mabeto** [BME-MIT-IET/Red-Frogs-iet-2019#6]
A manuális tesztek eredményei a [wiki](https://github.com/BME-MIT-IET/Red-Frogs-iet-2019/wiki/Manu%C3%A1lis-tesztel%C3%A9s-(mabeto)) oldalon találhatóak,

**Comment by TZsolt94** [comment]
Végrehajtottam a tervezett tesztjeidet és ugyanazokat az eredményeket kaptam.

**Comment by IncredibleK** [comment]
Futattam a teszteseteket a mobilomon és az eredmények nekem is ezek alapján jöttek ki, szép munka!
