### ISSUE TITLE
Manuális tesztelés TZsolt94

### ISSUE THREAD

**Issue by TZsolt94** [BME-MIT-IET/Red-Frogs-iet-2019#9]
A tesztelésem eredményei [itt](https://github.com/BME-MIT-IET/Red-Frogs-iet-2019/wiki/Manu%C3%A1lis-k%C3%B3d-%C3%A1tvizsg%C3%A1l%C3%A1s-TZsolt94) találhatóak.

**Comment by mabeto** [comment]
A tesztek megfelelően futottak nálam is.

**Comment by IncredibleK** [comment]
Megnéztem, az összes teszt sikeresen futott.
